FROM maven:3.9.12-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-alpine
VOLUME /tmp
COPY --from=build /app/target/*.jar app.jar
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV JWT_BASE64_SECRET=${JWT_BASE64_SECRET}
ENV CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV GMAIL=${GMAIL}
ENV GMAIL_PASSCODE=${GMAIL_PASSCODE}
ENV DATASOURCE_URL_PROD=${DATASOURCE_URL_PROD}
ENV DATASOURCE_USERNAME_PROD=${DATASOURCE_USERNAME_PROD}
ENV DATASOURCE_PASSWORD_PROD=${DATASOURCE_PASSWORD_PROD}
ENV DATASOURCE_URL_LOCAL=${DATASOURCE_URL_LOCAL}
ENV DATASOURCE_USER_LOCAL=${DATASOURCE_USER_LOCAL}
ENV DATASOURCE_PASSWORD_LOCAL=${DATASOURCE_PASSWORD_LOCAL}
ENV FRONTEND_URL_PROD=${FRONTEND_URL_PROD}
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
