spring.application.name=backend

spring.datasource.url=${DATASOURCE_URL_LOCAL}
spring.datasource.username=${DATASOURCE_USER_LOCAL}
spring.datasource.password=${DATASOURCE_PASSWORD_LOCAL}
frontend.url=${FRONTEND_URL_LOCAL}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}


